version: "3.9"

services:
  inventory:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mariadb
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres:14.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootroot
    ports:
      - "5432:5432"
    
  mariadb:
    container_name: mariadb_container
    image: mariadb:10.7.4
    restart: unless-stopped
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: rootroot
    ports: 
      - "3306:3306" #locat port : container port

  mysql:
    #build:
      #context: ./ 
      #dockerfile: rec/dkr/mysql/Dockerfile 
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    platform: linux/x86_64 #compatibity problem with M1
    image: mysql:8.0.29
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootroot
      #MYSQL_DATABASE: test_db
    ports:
      - "33066:33066"



   

    #volumes:
    #  - ./rec/dat/mysql:/var/lib/mysql
  