// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/wire
//go:build !wireinject
// +build !wireinject

package shared

import (
	"github.com/devpablocristo/golang/sdk/gateways/monitoring"
	"github.com/devpablocristo/golang/sdk/gateways/user"
	"github.com/devpablocristo/golang/sdk/internal/bootstrap/cassandra"
	user2 "github.com/devpablocristo/golang/sdk/internal/user"
)

// Injectors from wire.go:

func InitializeUserHandler() (*user.GinHandler, error) {
	cassandraClientPort, err := cassandrasetup.NewCassandraInstance()
	if err != nil {
		return nil, err
	}
	repository := user2.NewCassandraRepository(cassandraClientPort)
	userUseCases := user2.NewUserUseCases(repository)
	ginHandler := user.NewGinHandler(userUseCases)
	return ginHandler, nil
}

func InitializeMonitoring() (*monitoring.GinHandler, error) {
	ginHandler := monitoring.NewGinHandler()
	return ginHandler, nil
}
