version: "3.7"

services:
  mysql-local:
    container_name: mysql-local
    image: "mysql:8.2.0-oracle"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - default
    ports:
      - "${MYSQL_HOST_PORT:-3307}:${MYSQL_CONT_PORT:-3306}"
    expose:
      - "${MYSQL_HOST_PORT:-3307}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-test}"
      MYSQL_USER: "${MYSQL_USERNAME:-user}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD:-12345}"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "./.docker-volumes/mysql:/var/lib/mysql" #por coherencia con dynamodb, uso el directorio definido
      #- "mysql_data:/var/lib/mysql"
      - "./infra/database/*.sql:/docker-entrypoint-initdb.d/" #all scripts in docker-entrypoint-initdb.d/ are automatically executed during container startup

  dynamodb-local:
   command: "-jar DynamoDBLocal.jar -port 8765 -sharedDb -dbPath /home/dynamodblocal/data"
   image: "amazon/dynamodb-local:1.24.0"
   container_name: dynamodb-local
   restart: unless-stopped
   networks:
      - default
   ports:
     - 9876:8765
   expose:
     - 9876 # puerto para acceder desde afuera
   volumes:
     - "./.docker-volumes/dynamodb:/home/dynamodblocal/data" 
     #- "dynamodb_data:/home/dynamodblocal/data" #por problemas permisos no puedo usar el volumen

  api:
    container_name: api-local
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 9999:8888  
    expose:
      - 9999 # Puerto para Postman
    networks:
      - default  
    depends_on:
      - mysql-local
      - dynamodb-local
    links:
      - mysql-local
      - dynamodb-local  
    volumes:
      - "./:/app"
    environment:
      - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY:-fakeAccessKey}"
      - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_KEY:-fakeSecretKey}"
      - REGION="${AWS_REGION:-local}"

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin-local
    networks:
      - default    
    links:
      - mysql-local
    restart: always
    environment:
      - PMA_HOST="${MYSQL_CONT:-mysql-local}" #nombre del server "mysql-local" en este caso
      - PMA_PORT="${MYSQL_HOST_PORT:-3307}"
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-root}"
    ports:
      - "${PHPMYADMIN_HOST_PORT:-9090}:${PHPMYADMIN_CONT_PORT:-80}"

networks:
  default:

# supuestamente, esta por revisar, si podria usar mysql_data, pero no dynamodb_data, no se porque.
# por coherencia, hice ambos definidos
#volumes:
  #mysql_data:
  #dynamodb_data: #por problemas permisos no puedo usar el volumen
