version: "3.8"

services:
  api:
    container_name: ${APP_NAME:-events}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${ROUTER_PORT:-8080}:${ROUTER_TARGET_PORT:-8080}"
      - "${DELVE_PORT:-2345}:${DELVE_TARGET_PORT:-2345}"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./migrations
        target: /app/migrations  
    environment:
      - APP_NAME=${APP_NAME:-events}
      - DEBUG=true
      - DEV_DB_HOST=${DEV_DB_HOST:-postgres}
      - DEV_DB_HOST_PORT=${DEV_DB_HOST_PORT:-5432}
      - DEV_DB_DATABASE=${DEV_DB_DATABASE:-dev_events_db}
      - DEV_DB_USERNAME=${DEV_DB_USERNAME:-postgres}
      - DEV_DB_USER_PASSWORD=${DEV_DB_USER_PASSWORD:-root}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS:-http://consul:8500}
    depends_on:
      - postgres
      - consul
    networks:
      - default

  postgres:
    image: postgres:16.3
    container_name: postgres
    ports:
      - "${DEV_DB_HOST_PORT:-5432}:${DEV_DB_TARGET_PORT:-5432}"
    environment:
      POSTGRES_DB: ${DEV_DB_DATABASE:-dev_events_db}
      POSTGRES_USER: ${DEV_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DEV_DB_USER_PASSWORD:-root}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT:-8081}:${PGADMIN_TARGET_PORT:-80}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    logging:
      driver: "none"  
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  
    networks:
      - default

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "${CONSUL_PORT:-8500}:${CONSUL_TARGET_PORT:-8500}"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
