version: '3.8'

services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - consul
    networks:
      - app-network
    environment:
      - CONSUL_ADDRESS=consul:8500

networks:
  app-network:
    driver: bridge
