// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: book/book.proto

package book

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookstoreInventoryClient is the client API for BookstoreInventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookstoreInventoryClient interface {
	CreateNewBook(ctx context.Context, in *NewBook, opts ...grpc.CallOption) (*Book, error)
}

type bookstoreInventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewBookstoreInventoryClient(cc grpc.ClientConnInterface) BookstoreInventoryClient {
	return &bookstoreInventoryClient{cc}
}

func (c *bookstoreInventoryClient) CreateNewBook(ctx context.Context, in *NewBook, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/grpcbook.BookstoreInventory/CreateNewBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookstoreInventoryServer is the server API for BookstoreInventory service.
// All implementations must embed UnimplementedBookstoreInventoryServer
// for forward compatibility
type BookstoreInventoryServer interface {
	CreateNewBook(context.Context, *NewBook) (*Book, error)
	mustEmbedUnimplementedBookstoreInventoryServer()
}

// UnimplementedBookstoreInventoryServer must be embedded to have forward compatible implementations.
type UnimplementedBookstoreInventoryServer struct {
}

func (UnimplementedBookstoreInventoryServer) CreateNewBook(context.Context, *NewBook) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewBook not implemented")
}
func (UnimplementedBookstoreInventoryServer) mustEmbedUnimplementedBookstoreInventoryServer() {}

// UnsafeBookstoreInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookstoreInventoryServer will
// result in compilation errors.
type UnsafeBookstoreInventoryServer interface {
	mustEmbedUnimplementedBookstoreInventoryServer()
}

func RegisterBookstoreInventoryServer(s grpc.ServiceRegistrar, srv BookstoreInventoryServer) {
	s.RegisterService(&BookstoreInventory_ServiceDesc, srv)
}

func _BookstoreInventory_CreateNewBook_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(NewBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreInventoryServer).CreateNewBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcbook.BookstoreInventory/CreateNewBook",
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BookstoreInventoryServer).CreateNewBook(ctx, req.(*NewBook))
	}
	return interceptor(ctx, in, info, handler)
}

// BookstoreInventory_ServiceDesc is the grpc.ServiceDesc for BookstoreInventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookstoreInventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcbook.BookstoreInventory",
	HandlerType: (*BookstoreInventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewBook",
			Handler:    _BookstoreInventory_CreateNewBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book/book.proto",
}
