version: '3.7'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "9000:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - .:/app/data
  mysql:
    container_name: mysql-repo
    platform: linux/x86_64 #compatibity problem with M1
    image: mysql:8.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'  # Opens port 3306 on the container
    environment:
      MYSQL_DATABASE: items
      MYSQL_USER: tester
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes: # we mount a data volume to make sure we don't lose data
      - mysql-data:/var/lib/mysql # Where our data will be persisted
    command: --default-authentication-plugin=mysql_native_password

  # se agrega el servicio de phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql-repo
      MYSQL_ROOT_PASSWORD: secret

networks:
  default:

volumes:
  mysql-data:






# services:
#   postgres:
#     container_name: postgres_container
#     image: postgres:14.4
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: rootroot
#     ports:
#       - "5432:5432"
    
#   mariadb:
#     container_name: mariadb_container
#     image: mariadb:10.7.4
#     restart: unless-stopped
#     environment:
#       MARIADB_USER: root
#       MARIADB_ROOT_PASSWORD: rootroot
#     ports: 
#       - "3306:3306" #locat port : container port

#   mysql:
#     container_name: mysql_container
#     platform: linux/x86_64 #compatibity problem with M1
#     image: mysql:8.0
#     restart: unless-stopped
#     environment:
#       MYSQL_USER: root
#       MYSQL_ROOT_PASSWORD: rootroot
#     ports:
#       - "33066:33006"