FROM golang:1.22.3-alpine3.20

# Instalar git, Go tools (Delve y Air), y tzdata para configurar la zona horaria
RUN apk update && apk add --no-cache git tzdata && \
    go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/air-verse/air@latest && \
    rm -rf /var/cache/apk/*

# Configurar la zona horaria a Buenos Aires, Argentina
ENV TZ=America/Argentina/Buenos_Aires

# Crear un enlace simbólico a la zona horaria correcta
RUN cp /usr/share/zoneinfo/America/Argentina/Buenos_Aires /etc/localtime && \
    echo "America/Argentina/Buenos_Aires" > /etc/timezone

# Agregar el directorio bin de Go al PATH
ENV PATH="/root/go/bin:${PATH}"

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . .

# Asegurarse de que el script de entrypoint sea ejecutable
RUN chmod +x /app/scripts/entrypoint.sh

# Instalar dependencias de Go
RUN go mod download && go mod verify

# Crear el directorio tmp si no existe
RUN mkdir -p /app/tmp

# Exponer los puertos necesarios
EXPOSE 8080 2345

# Definir el script de entrypoint para el contenedor
ENTRYPOINT ["/app/scripts/entrypoint.sh"]
