FROM golang:1.22.3-alpine3.20

# Install git and Go tools (Delve and Air) for debugging and live reloading
RUN apk update && apk add --no-cache git && \
    go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/air-verse/air@latest && \
    rm -rf /var/cache/apk/*

# Add Go bin directory to PATH (ensures Air is in the PATH)
ENV PATH="/root/go/bin:${PATH}"

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the project files to the container
COPY . .

# Ensure the entrypoint script is executable
RUN chmod +x /app/scripts/entrypoint.sh

# Install Go dependencies
RUN go mod download && go mod verify

# Create the bin directory if it doesn't exist
RUN mkdir -p /app/tmp

# Expose the necessary ports
EXPOSE 8080 2345

# Define the entrypoint script for the container
ENTRYPOINT ["/app/scripts/entrypoint.sh"]
