FROM golang:1.22.3-alpine3.20

# Install dependencies and Delve for debugging
RUN apk update && \
    apk add --no-cache bash git libc-dev g++ inotify-tools curl && \
    go install github.com/go-delve/delve/cmd/dlv@latest

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the project files to the container
COPY . .
# config nueva, funciona bien pero probar
RUN chmod +x /app/scripts/entrypoint.sh
RUN go mod download && go mod verify

# Create the bin directory if it doesn't exist
RUN mkdir -p /app/bin

# Expose the necessary ports
EXPOSE 8080 2345

# Define the entrypoint script for the container
CMD ["/app/scripts/entrypoint.sh"]
