// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book/book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewBook struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBook) Reset()         { *m = NewBook{} }
func (m *NewBook) String() string { return proto.CompactTextString(m) }
func (*NewBook) ProtoMessage()    {}
func (*NewBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{0}
}

func (m *NewBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBook.Unmarshal(m, b)
}
func (m *NewBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBook.Marshal(b, m, deterministic)
}
func (m *NewBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBook.Merge(m, src)
}
func (m *NewBook) XXX_Size() int {
	return xxx_messageInfo_NewBook.Size(m)
}
func (m *NewBook) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBook.DiscardUnknown(m)
}

var xxx_messageInfo_NewBook proto.InternalMessageInfo

func (m *NewBook) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewBook) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type Book struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*NewBook)(nil), "grpcbook.NewBook")
	proto.RegisterType((*Book)(nil), "grpcbook.Book")
}

func init() {
	proto.RegisterFile("book/book.proto", fileDescriptor_ee9082fb44230b1b)
}

var fileDescriptor_ee9082fb44230b1b = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xca, 0xcf, 0xcf,
	0xd6, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x1c, 0xe9, 0x45, 0x05, 0xc9, 0x20,
	0xbe, 0x92, 0x39, 0x17, 0xbb, 0x5f, 0x6a, 0xb9, 0x53, 0x7e, 0x7e, 0xb6, 0x90, 0x08, 0x17, 0x6b,
	0x49, 0x66, 0x49, 0x4e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0x23, 0x24, 0xc6,
	0xc5, 0x96, 0x58, 0x5a, 0x92, 0x91, 0x5f, 0x24, 0xc1, 0x04, 0x16, 0x86, 0xf2, 0x94, 0x5c, 0xb8,
	0x58, 0x48, 0xd7, 0x25, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1a,
	0xc4, 0x94, 0x99, 0x62, 0xe4, 0xc5, 0x25, 0x04, 0x32, 0xa5, 0xb8, 0x24, 0xbf, 0x28, 0xd5, 0x33,
	0xaf, 0x2c, 0x35, 0xaf, 0x24, 0xbf, 0xa8, 0x52, 0xc8, 0x84, 0x8b, 0xd7, 0xb9, 0x28, 0x35, 0xb1,
	0x24, 0x15, 0xe6, 0x34, 0x41, 0x3d, 0x98, 0x83, 0xf5, 0xa0, 0x42, 0x52, 0x7c, 0x08, 0x21, 0x10,
	0x5f, 0x89, 0xc1, 0xc9, 0x3e, 0xca, 0x36, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f,
	0x57, 0x3f, 0x25, 0xb5, 0xac, 0x20, 0x31, 0x29, 0x27, 0x3f, 0xb9, 0x28, 0xb3, 0xb8, 0x24, 0x5f,
	0x3f, 0x3d, 0x3f, 0x27, 0x31, 0x2f, 0x5d, 0x37, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5, 0x58,
	0x1f, 0xa4, 0x19, 0x1c, 0x22, 0x60, 0xab, 0xc1, 0xac, 0x24, 0x36, 0x70, 0xe0, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xe2, 0xe3, 0xaf, 0x34, 0x2f, 0x01, 0x00, 0x00,
}
