version: "3.7"
services:
  vscode:
    image: devpablocristo/godevcontainer
    container_name: godevcontainer
    build:
      #dockerfile: alpine2.Dockerfile
      #dockerfile: alpine.Dockerfile
      dockerfile: debian.Dockerfile
      context: ./
    ports:
      - "${LOCAL_PORT}:${CONTAINER_PORT}"
    volumes:
      - ./:/app
      - ../:/workspace
    env_file:
      - .env