version: '3.7'
services:
  backend:
    container_name: node_pitichis
    image: node_pitichis:1
    build: 
      context: .
      dockerfile: Dockerfile.dev     
    working_dir: /app 
    ports:
      - '8080:8080'
    volumes:
      - /app/node_modules
      - .:/app:cached
    tty: true