version: "3.7"
services:
  go-gin-service:
    #image: devpablocristo/go-gin-service:0.1-alpine2
    #image: devpablocristo/go-gin-service:0.1-alpine
    image: devpablocristo/go-gin-service:0.1
    container_name: go-gin-service
    build:
      #dockerfile: alpine2.Dockerfile
      #dockerfile: alpine.Dockerfile
      dockerfile: debian.Dockerfile
      context: ./
    ports:
      - "${LOCAL_PORT}:${CONTAINER_PORT}"
    volumes:
      - ./:/app
    env_file:
      - .env