version: '3.7'
services:

  mysql:
    image: mysql:8.0.2
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_LOCL_PORT}:${MYSQL_CONT_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVICE_TAGS=${MYSQL_SERVICE_TAGS}
      - SERVICE_NAME=${MYSQL_SERVICE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    #env_file:
    #  - variables.env
    #networks:
    #  - gin-gonic

  phpmyadmin:
    image: phpmyadmin:5.1.0
    restart: always
    container_name: phpmyadmin
    ports:
      - ${MYADM_LOCL_PORT}:${MYADM_CONT_PORT}
    environment:
      - PMA_HOST=mysql
      - ${MYSQL_ROOT_PASSWORD}=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    #env_file:
    #  - variables.env
    #networks:
    #  - gin-gonic

  mongodb:
    image: mongo:4.4.6
    #networks:
    #  - gin-gonic

  service:
    image: devpablocristo/gin-gonic:0.1
    container_name: service
    build:
      dockerfile: debian.Dockerfile
      context: ./
    ports:
      - ${SERV_LOCL_PORT}:${SERV_CONT_PORT}
    volumes:
      - ./:/app
    #env_file:
    #  - ./variables.env
    #networks:
    #  - gingonic

volumes:
  mysql_data: