# pull official base image
FROM node:15.0.1-alpine3.11 as dev

#RUN npm install -g create-react-app 

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
#COPY origen destino
COPY package*.json ./
RUN npm install --silent
RUN npm install -g react-scripts@4.0.0 --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]