version: '3.7'
services:
    app:
      container_name: app
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - './:/app:cached' 
        - '/app/node_modules'
      working_dir: /app 
      ports:
        - 3000:3000
      command: npm start
      environment:
        - CHOKIDAR_USEPOLLING=true
      tty: true
