version: "3.8"

services:
  rest:
    container_name: "${APP_NAME:-golang-sdk}"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${ROUTER_PORT:-8080}:${ROUTER_TARGET_PORT:-8080}"
      - "${DELVE_PORT:-2345}:${DELVE_TARGET_PORT:-2345}"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./migrations
        target: /app/migrations
    environment:
      - APP_NAME=${APP_NAME:-golang-sdk}
      - DEBUG=true
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT:-5432}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-dev_events_db}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_USER_PASSWORD=${POSTGRES_USER_PASSWORD:-root}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS:-http://consul:8500}
      - CONSUL_ID=${CONSUL_ID:-rest}
      - CONSUL_NAME=${CONSUL_NAME:-rest}
      - CONSUL_SERVICE_NAME=${CONSUL_SERVICE_NAME:-rest}
      - CONSUL_HEALTH_CHECK=${CONSUL_HEALTH_CHECK:-http://rest:8080/health}
      - CONSUL_CHECK_INTERVAL=${CONSUL_CHECK_INTERVAL:-10s}
      - CONSUL_CHECK_TIMEOUT=${CONSUL_CHECK_TIMEOUT:-1s}
      - CONSUL_PORT=${CONSUL_PORT:-8500}
      - CASSANDRA_HOST=${CASSANDRA_HOST:-cassandra}
      - CASSANDRA_PORT=${CASSANDRA_PORT:-9042}
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME:-cassandra}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD:-cassandra}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE:-dev_keyspace}
      - CASSANDRA_REPLICATION_FACTOR=${CASSANDRA_REPLICATION_FACTOR:-3}
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME:-CassandraCluster}
      - CASSANDRA_DC=${CASSANDRA_DC:-datacenter1}
      - CASSANDRA_RACK=${CASSANDRA_RACK:-rack1}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH:-GossipingPropertyFileSnitch}
      - REDIS_ADDRESS=${REDIS_ADDRESS:-redis:6379}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - REDIS_DB=${REDIS_DB:-0}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-dev_events_db}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
      - PYROSCOPE_SERVER_ADDRESS=${PYROSCOPE_SERVER_ADDRESS:-http://pyroscope-server:4040}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-rootpassword}
      - MONGO_HOST=${MONGO_HOST:-mongodb}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}      # Añadido
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}          # Añadido
      - RABBITMQ_MANAGEMENT_PORT=${RABBITMQ_MANAGEMENT_PORT:-15672} # Añadido
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-user}        # Añadido
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-password}    # Añadido
      - DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT:-http://dynamodb:8765} # Añadido
      - DYNAMODB_PORT=${DYNAMODB_PORT:-8765}          # Añadido
      - DYNAMODB_REGION=${DYNAMODB_REGION:-us-west-2} # Añadido
    depends_on:
      - postgres
      - consul
      - cassandra
      - mysql
      - redis
      - prometheus
      - grafana
      - pyroscope
      - mongodb
      - rabbitmq
      - dynamodb
    networks:
      - app-network
    restart: on-failure

  postgres:
    image: postgres:16.3
    container_name: postgres
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:${POSTGRES_HOST_PORT:-5432}"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-dev_events_db}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:-root}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT:-8081}:${PGADMIN_PORT:-80}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    logging:
      driver: "none"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    restart: on-failure

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "${CONSUL_PORT:-8500}:${CONSUL_PORT:-8500}"
    networks:
      - app-network
    restart: on-failure

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "${CASSANDRA_PORT:-9042}:${CASSANDRA_PORT:-9042}"
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME:-CassandraCluster}
      - CASSANDRA_DC=${CASSANDRA_DC:-datacenter1}
      - CASSANDRA_RACK=${CASSANDRA_RACK:-rack1}
      - CASSANDRA_SEEDS=${CASSANDRA_HOST:-cassandra}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH:-GossipingPropertyFileSnitch}
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME:-cassandra}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD:-cassandra}
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - app-network
    restart: on-failure

  datastax-studio:
    image: datastax/dse-studio:6.8.32
    container_name: datastax-studio
    ports:
      - "${DS_PORT:-9091}:${DS_PORT:-9091}"
    depends_on:
      - cassandra
    environment:
      - DS_LICENSE=accept
    networks:
      - app-network
    restart: on-failure

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    networks:
      - app-network
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-dev_events_db}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8082}:${PHPMYADMIN_PORT:-80}"
    environment:
      - PMA_HOST=${PMA_HOST:-mysql}
      - PMA_USER=${MYSQL_USER:-root}
      - PMA_PASSWORD=${MYSQL_PASSWORD:-root}
    depends_on:
      - mysql
    networks:
      - app-network
    restart: on-failure

  prometheus:
    image: prom/prometheus:v2.45.6
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT:-9090}:${PROMETHEUS_PORT:-9090}"
    networks:
      - app-network
    restart: on-failure

  grafana:
    image: grafana/grafana:10.2.8
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:${GRAFANA_PORT:-3000}"
    depends_on:
      - prometheus
    networks:
      - app-network
    restart: on-failure

  pyroscope:
    image: grafana/pyroscope:weekly-f76-feefa815b
    container_name: pyroscope
    ports:
      - "${PYROSCOPE_PORT:-4040}:${PYROSCOPE_PORT:-4040}"
    volumes:
      - pyroscope_data:/var/lib/pyroscope
    networks:
      - app-network
    restart: on-failure

  mongodb:
    image: mongo:5.0.28
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-rootpassword}
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: on-failure

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-rootpassword}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST:-mongodb}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL:-mongodb://root:rootpassword@mongodb:27017/}
    ports:
      - "${ME_PORT:-8083}:${ME_PORT:-8081}"
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: on-failure

  ngrok:
    image: ngrok/ngrok:3.13.0-alpine-91be825
    container_name: ngrok
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "${NGROK_PORT:-5050}:${NGROK_PORT:-5050}"
    networks:
      - app-network
    depends_on:
      - rest
    restart: on-failure

  kong-migrations:
    image: kong:2.8.5-alpine
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=${KONG_DATABASE:-postgres}
      - KONG_PG_HOST=${POSTGRES_HOST:-postgres}
      - KONG_PG_PORT=${POSTGRES_HOST_PORT:-5432}
      - KONG_PG_USER=${POSTGRES_USERNAME:-postgres}
      - KONG_PG_PASSWORD=${POSTGRES_USER_PASSWORD:-root}
      - KONG_PG_DATABASE=${POSTGRES_DATABASE:-dev_events_db}
    depends_on:
      - postgres
    networks:
      - app-network

  kong:
    image: kong:2.8.5-alpine
    container_name: kong
    environment:
      - KONG_DATABASE=${KONG_DATABASE:-postgres}
      - KONG_PG_HOST=${POSTGRES_HOST:-postgres}
      - KONG_PG_PORT=${POSTGRES_HOST_PORT:-5432}
      - KONG_PG_USER=${POSTGRES_USERNAME:-postgres}
      - KONG_PG_PASSWORD=${POSTGRES_USER_PASSWORD:-root}
      - KONG_PG_DATABASE=${POSTGRES_DATABASE:-dev_events_db}
      - KONG_PROXY_ACCESS_LOG=${KONG_PROXY_ACCESS_LOG:-/dev/stdout}
      - KONG_ADMIN_ACCESS_LOG=${KONG_ADMIN_ACCESS_LOG:-/dev/stdout}
      - KONG_PROXY_ERROR_LOG=${KONG_PROXY_ERROR_LOG:-/dev/stderr}
      - KONG_ADMIN_ERROR_LOG=${KONG_ADMIN_ERROR_LOG:-/dev/stderr}
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN:-0.0.0.0:8001}
    ports:
      - "${KONG_PROXY_PORT:-8000}:${KONG_PROXY_PORT:-8000}"
      - "${KONG_PROXY_SSL_PORT:-8443}:${KONG_PROXY_SSL_PORT:-8443}"
      - "${KONG_ADMIN_PORT:-8001}:${KONG_ADMIN_PORT:-8001}"
      - "${KONG_ADMIN_SSL_PORT:-8444}:${KONG_ADMIN_SSL_PORT:-8444}"
    depends_on:
      - kong-migrations
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-password}
    ports:
      - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:${RABBITMQ_MANAGEMENT_PORT:-15672}"
    networks:
      - app-network
    restart: on-failure

  dynamodb:
    image: amazon/dynamodb-local:1.24.0
    container_name: dynamodb
    command: "-jar DynamoDBLocal.jar -port ${DYNAMODB_PORT:-8765} -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - "${DYNAMODB_PORT:-8765}:${DYNAMODB_PORT:-8765}"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  cassandra_data:
  mysql_data:
  pyroscope_data:
  mongodb_data:
  dynamodb_data:
