version: "3.8"
services:
  mysql-local:
    container_name: mysql-local
    image: "mysql:8.2.0-oracle"
    command: >
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-tarefaapi}"
      MYSQL_USER: "${MYSQL_USERNAME:-user}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD:-12345}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST:-%}"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_HOST_PORT:-3307}:${MYSQL_CONT_PORT:-3306}"
    networks:
      - api-local-network

  api-local:
    container_name: api-local
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "${API_LOCAL_PORT:-9999}:8080"
    depends_on:
      - mysql-local
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      - api-local-network

  phpmyadmin-local:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin-local
    environment:
      PMA_HOST: "mysql-local"
      PMA_PORT: "${MYSQL_CONT_PORT:-3306}"
      PMA_ARBITRARY: "${PMA_ARBITRARY:-1}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
    ports:
      - "${PHPMYADMIN_HOST_PORT:-9090}:${PHPMYADMIN_CONT_PORT:-80}"
    networks:
      - api-local-network
    depends_on:
      - mysql-local

  elasticsearch-local:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch-local
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS="${ES_JAVA_OPTS:--Xmx512m -Xms512m}"
      - xpack.security.enabled="${XPACK_SECURITY_ENABLED:-false}"
      - node.name="${ES_NODE_NAME:-elasticsearch-local}"
      - cluster.name="${ES_CLUSTER_NAME:-es-docker-cluster}"
      - bootstrap.memory_lock="${ES_BOOTSTRAP_MEMORY_LOCK:-true}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - api-local-network

  rabbitmq-local:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - api-local-network

volumes:
  mysql_data:
    name: mysql_data
  data01:
    name: data01
  rabbitmq:
    name: rabbitmq

networks:
  api-local-network:
    name: api-local-network
