version: "3.5"
services:
  mysql: 
    image: mysql:8.0
    container_name: golang-hex-arch-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persons
      MYSQL_USER: user  
      MYSQL_PASSWORD: user
    volumes:
      - ./schema/persons:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306 #host:container
  
  golang-rest:
    build: .
    container_name: golang-hex-arch-server
    restart: always
    environment:
      - DB_DRIVER="mysql"
      - DB_NAME="root:root" #user:passw
    depends_on:
      - db
    command: ["go", "test", "-v", "./..."]
   
    ports: 
      - 8000:8000
      - 9000:9000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    tty: true
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=golang-mysql
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8081:80
