// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/devpablocristo/golang/sdk/cmd/rest/monitoring/handler"
	"github.com/devpablocristo/golang/sdk/cmd/rest/user/handler"
	"github.com/devpablocristo/golang/sdk/internal/core"
	user2 "github.com/devpablocristo/golang/sdk/internal/core/user"
	"github.com/devpablocristo/golang/sdk/internal/platform/cassandra"
)

// Injectors from wire.go:

func InitializeUserHandler() (*user.Handler, error) {
	cassandraClientPort, err := cassandrasetup.NewCassandraInstance()
	if err != nil {
		return nil, err
	}
	repositoryPort := user2.NewUserRepository(cassandraClientPort)
	userUseCasePort := core.NewUserUseCase(repositoryPort)
	handler := user.NewHandler(userUseCasePort)
	return handler, nil
}

func InitializeMonitoring() (*monitoring.Handler, error) {
	handler := monitoring.NewHandler()
	return handler, nil
}
